<?php
/**
 * KloudStack Migration — Background Export Engine
 *
 * Manages async jobs for DB dump and media ZIP creation + Azure Blob upload.
 * Uses WP-Cron for scheduling: process_queue() runs every 60 seconds.
 *
 * Job lifecycle:
 *   queued → processing → complete | failed
 *
 * DB export:
 *   1. Shell-out to mysqldump (respects WP DB constants)
 *   2. Gzip the output (inline pipe to save disk space)
 *   3. Upload the gzipped dump to Azure Blob via SAS PUT request
 *   4. Update job transient → complete
 *
 * Media upload:
 *   1. Create a ZIP archive of wp-content/uploads/*
 *   2. Stream upload to Azure Blob via SAS PUT request using chunked transfer
 *   3. Update job transient → complete
 *
 * Security:
 *   - mysqldump credentials taken from WP_DB_* constants (never user input)
 *   - Command arguments individually escaped with escapeshellarg()
 *   - SAS URLs validated to be HTTPS before use
 *   - Temp files created in sys_get_temp_dir() with unique names and deleted after use
 *
 * @package KloudStackMigration
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class KloudStack_Migration_BackgroundExport {

    const CRON_HOOK    = 'kloudstack_process_export_queue';
    const QUEUE_OPTION = 'kloudstack_export_queue';

    // Max concurrent jobs processed per cron tick
    const MAX_JOBS_PER_RUN = 1;

    // Chunk size for streaming upload: 4 MB
    const UPLOAD_CHUNK_SIZE = 4 * 1024 * 1024;

    // ------------------------------------------------------------------
    // Cron setup
    // ------------------------------------------------------------------

    public static function setup_cron(): void {
        if ( ! wp_next_scheduled( self::CRON_HOOK ) ) {
            wp_schedule_event( time(), 'every_minute', self::CRON_HOOK );
        }
        add_filter( 'cron_schedules', [ __CLASS__, 'add_cron_interval' ] );
        add_action( self::CRON_HOOK, [ __CLASS__, 'process_queue' ] );
    }

    public static function add_cron_interval( array $schedules ): array {
        if ( ! isset( $schedules['every_minute'] ) ) {
            $schedules['every_minute'] = [
                'interval' => 60,
                'display'  => 'Every Minute',
            ];
        }
        return $schedules;
    }

    // ------------------------------------------------------------------
    // Queue management
    // ------------------------------------------------------------------

    /**
     * Enqueue a new export job.
     *
     * @param string $job_id   Unique job ID (generated by RestEndpoints)
     * @param string $type     'db_export' | 'media_upload'
     * @param string $sas_url  Azure Blob SAS URL for uploading
     */
    public static function enqueue( string $job_id, string $type, string $sas_url ): void {
        $queue   = get_option( self::QUEUE_OPTION, [] );
        $queue[] = [
            'job_id'  => $job_id,
            'type'    => $type,
            'sas_url' => $sas_url,
        ];
        update_option( self::QUEUE_OPTION, $queue, false );
    }

    /**
     * Process the next job(s) from the queue.
     * Called by WP-Cron every minute.
     */
    public static function process_queue(): void {
        // Prevent concurrent execution. The shutdown function registered by export_db /
        // upload_media and WP-Cron can both fire process_queue() at the same time.
        // A transient-based mutex stops double-processing and double resource usage.
        $lock_key = 'ks_mig_queue_lock';
        if ( get_transient( $lock_key ) ) {
            return; // Another invocation is already running — skip silently
        }
        // TTL = 10 min. Auto-expires if the process is killed before the finally block.
        set_transient( $lock_key, 1, 600 );

        try {
            $queue = get_option( self::QUEUE_OPTION, [] );
            if ( empty( $queue ) ) {
                return;
            }

            $processed = 0;
            $remaining = [];

            foreach ( $queue as $item ) {
                if ( $processed >= self::MAX_JOBS_PER_RUN ) {
                    $remaining[] = $item;
                    continue;
                }

                $job_id  = $item['job_id'];
                $type    = $item['type'];
                $sas_url = $item['sas_url'];

                // Mark as processing
                self::_update_job( $job_id, [ 'status' => 'processing', 'progress' => 5 ] );

                $success = false;
                try {
                    if ( 'db_export' === $type ) {
                        $success = self::_run_db_export( $job_id, $sas_url );
                    } elseif ( 'media_upload' === $type ) {
                        $success = self::_run_media_upload( $job_id, $sas_url );
                    }
                } catch ( Exception $e ) {
                    self::_update_job( $job_id, [
                        'status' => 'failed',
                        'error'  => substr( $e->getMessage(), 0, 500 ),
                    ] );
                    error_log( "KloudStack Migration: job {$job_id} failed: " . $e->getMessage() );
                }

                if ( $success ) {
                    self::_update_job( $job_id, [ 'status' => 'complete', 'progress' => 100 ] );
                } elseif ( 'failed' !== self::_job_status( $job_id ) ) {
                    $remaining[] = $item; // Re-queue if not explicitly marked failed
                }

                $processed++;
            }

            update_option( self::QUEUE_OPTION, $remaining, false );
        } finally {
            delete_transient( $lock_key );
        }
    }

    // ------------------------------------------------------------------
    // DB Export
    // ------------------------------------------------------------------

    /**
     * Export the WordPress database to a gzipped dump and upload to Azure Blob.
     *
     * Uses mysqldump piped through gzip, writing to a temp file, then
     * uploads via HTTP PUT to the SAS URL.
     *
     * @param string $job_id
     * @param string $sas_url  Must be HTTPS
     * @return bool  true on success
     * @throws Exception  on mysqldump failure or upload failure
     */
    private static function _run_db_export( string $job_id, string $sas_url ): bool {
        self::_validate_sas_url( $sas_url );

        // exec() is required for mysqldump. Available by default on Azure App Service
        // Linux, but may be disabled on some shared hosting environments.
        if ( ! function_exists( 'exec' ) ) {
            throw new Exception( 'Database export requires exec() which is not available on this server. Contact your hosting provider.' );
        }

        $tmp_file = tempnam( sys_get_temp_dir(), 'ks_db_' ) . '.sql.gz';

        try {
            // Build mysqldump command with individual argument escaping
            $host     = escapeshellarg( DB_HOST );
            $user     = escapeshellarg( DB_USER );
            $database = escapeshellarg( DB_NAME );
            $tmp_esc  = escapeshellarg( $tmp_file );

            // DB_PASSWORD is passed via env var to avoid appearing on process list
            putenv( 'MYSQL_PWD=' . DB_PASSWORD );

            // gzip -4 balances compression vs CPU cost.
            // gzip -9 (max) spikes CPU heavily on Azure App Service Consumption plans.
            $cmd = "mysqldump --host={$host} --user={$user} --single-transaction "
                 . "--routines --triggers --add-drop-table {$database} "
                 . "| gzip -4 > {$tmp_esc} 2>&1";

            $output    = [];
            $exit_code = 0;
            exec( $cmd, $output, $exit_code );

            // Clear password from environment immediately
            putenv( 'MYSQL_PWD=' );

            if ( 0 !== $exit_code ) {
                throw new Exception( 'mysqldump failed (exit=' . $exit_code . '): ' . implode( ' ', $output ) );
            }

            if ( ! file_exists( $tmp_file ) || 0 === filesize( $tmp_file ) ) {
                throw new Exception( 'mysqldump produced empty output.' );
            }

            self::_update_job( $job_id, [ 'progress' => 70 ] );

            // Upload to Azure Blob via SAS PUT
            self::_upload_file_to_blob( $sas_url, $tmp_file, 'application/gzip' );

            self::_update_job( $job_id, [ 'progress' => 100 ] );
            return true;

        } finally {
            // Always clean up temp file
            if ( file_exists( $tmp_file ) ) {
                unlink( $tmp_file );
            }
            putenv( 'MYSQL_PWD=' );
        }
    }

    // ------------------------------------------------------------------
    // Media Upload
    // ------------------------------------------------------------------

    /**
     * Create a ZIP of wp-content/uploads and upload to Azure Blob.
     *
     * @param string $job_id
     * @param string $sas_url  Must be HTTPS
     * @return bool
     * @throws Exception
     */
    private static function _run_media_upload( string $job_id, string $sas_url ): bool {
        self::_validate_sas_url( $sas_url );

        if ( ! class_exists( 'ZipArchive' ) ) {
            throw new Exception( 'PHP ZipArchive extension is not available.' );
        }

        $uploads_dir = wp_upload_dir();
        $base_dir    = $uploads_dir['basedir'];

        if ( ! is_dir( $base_dir ) ) {
            throw new Exception( "Uploads directory not found: {$base_dir}" );
        }

        $tmp_zip = tempnam( sys_get_temp_dir(), 'ks_media_' ) . '.zip';

        try {
            $zip = new ZipArchive();
            if ( true !== $zip->open( $tmp_zip, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
                throw new Exception( "Cannot create ZIP archive at {$tmp_zip}" );
            }

            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator( $base_dir, FilesystemIterator::SKIP_DOTS ),
                RecursiveIteratorIterator::LEAVES_ONLY
            );

            $file_count = 0;
            foreach ( $iterator as $file ) {
                if ( $file->isFile() ) {
                    $relative_path = str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $file->getPathname() );
                    $zip->addFile( $file->getPathname(), $relative_path );
                    $file_count++;

                    // Update progress periodically during the zip phase (5–55%).
                    // ZipArchive::addFile() only stores the path reference — actual
                    // file data is compressed at close() time, so no memory flush
                    // is needed here.
                    if ( 0 === $file_count % 100 ) {
                        self::_update_job( $job_id, [ 'progress' => min( 55, 5 + (int) ( $file_count / 20 ) ) ] );
                    }
                }
            }

            $zip->close();

            if ( ! file_exists( $tmp_zip ) || 0 === filesize( $tmp_zip ) ) {
                throw new Exception( 'ZIP archive creation produced empty output.' );
            }

            self::_update_job( $job_id, [ 'progress' => 65 ] );

            // Upload to Azure Blob via SAS PUT
            self::_upload_file_to_blob( $sas_url, $tmp_zip, 'application/zip' );

            return true;

        } finally {
            if ( file_exists( $tmp_zip ) ) {
                unlink( $tmp_zip );
            }
        }
    }

    // ------------------------------------------------------------------
    // Azure Blob upload helper
    // ------------------------------------------------------------------

    /**
     * Upload a local file to an Azure Blob using a SAS PUT URL.
     *
     * Uses wp_remote_request with chunked streaming to handle large files
     * without exhausting PHP memory.
     *
     * @param string $sas_url    Must be HTTPS
     * @param string $local_path Full filesystem path to the file
     * @param string $mime_type  MIME type for Content-Type header
     * @throws Exception on upload failure
     */
    private static function _upload_file_to_blob( string $sas_url, string $local_path, string $mime_type ): void {
        $file_size = filesize( $local_path );
        $fh        = fopen( $local_path, 'rb' );

        if ( false === $fh ) {
            throw new Exception( "Cannot open file for upload: {$local_path}" );
        }

        try {
            // Use cURL streaming PUT to avoid loading the entire file into memory.
            // wp_remote_request() passes the body as a string (file_get_contents)
            // which OOMs on large DB dumps / media ZIPs on Azure App Service
            // (default memory_limit is 128 MB).
            $ch = curl_init( $sas_url );
            curl_setopt_array( $ch, [
                CURLOPT_PUT            => true,
                CURLOPT_INFILE         => $fh,
                CURLOPT_INFILESIZE     => $file_size,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT        => 3600,
                CURLOPT_HTTPHEADER     => [
                    'Content-Type: ' . $mime_type,
                    'x-ms-blob-type: BlockBlob',
                    'Expect:',  // Suppress 100-Continue handshake delay with Azure
                ],
            ] );

            $body      = curl_exec( $ch );
            $http_code = (int) curl_getinfo( $ch, CURLINFO_HTTP_CODE );
            $curl_err  = curl_error( $ch );
            curl_close( $ch );

            if ( $curl_err ) {
                throw new Exception( 'cURL upload error: ' . $curl_err );
            }

            if ( $http_code < 200 || $http_code >= 300 ) {
                throw new Exception( "Azure Blob upload failed (HTTP {$http_code}): " . substr( (string) $body, 0, 300 ) );
            }
        } finally {
            fclose( $fh );
        }
    }

    // ------------------------------------------------------------------
    // Job helpers
    // ------------------------------------------------------------------

    private static function _update_job( string $job_id, array $updates ): void {
        $transient_key = KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id;
        $job           = get_transient( $transient_key );
        if ( false === $job ) {
            return;
        }
        $job = array_merge( $job, $updates );
        set_transient( $transient_key, $job, KloudStack_Migration_RestEndpoints::JOB_TTL );
    }

    private static function _job_status( string $job_id ): string {
        $transient_key = KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id;
        $job           = get_transient( $transient_key );
        return $job['status'] ?? 'unknown';
    }

    /**
     * Validate that a SAS URL is HTTPS to prevent SSRF via HTTP downgrade.
     *
     * @param string $sas_url
     * @throws Exception if URL is not HTTPS
     */
    private static function _validate_sas_url( string $sas_url ): void {
        if ( empty( $sas_url ) ) {
            throw new Exception( 'SAS URL is empty.' );
        }
        if ( 0 !== strpos( $sas_url, 'https://' ) ) {
            throw new Exception( 'SAS URL must use HTTPS.' );
        }
        // Basic host check — must point to .blob.core.windows.net
        $host = parse_url( $sas_url, PHP_URL_HOST );
        if ( false === strpos( $host, '.blob.core.windows.net' ) ) {
            throw new Exception( "SAS URL host is not a trusted Azure Blob endpoint: {$host}" );
        }
    }
}
